version: '3.8'

services:
  yamnet-analyzer:
    build: ./yamnet_model
    stdin_open: true
    tty: true
    volumes:
      - ./UrbanSound8K:/app/UrbanSound8K               # dati in input
      - ./dati:/app/output                             # directory di output
    environment:
      - PYTHONUNBUFFERED=1