version: '3.8'

services:
  yamnet-analyzer:
    build: ./yamnet_model
    volumes:
      - ./UrbanSound8K:/app/UrbanSound8K  # monta i file audio come cartella
    environment:
      - PYTHONUNBUFFERED=1    #dice a Python di non bufferizzare l’output
